### ISSUE TITLE
Arrow starting from the wrong View

### ISSUE THREAD

**Issue by chriscz** [chilit-nl/plantuml-event-modeling#6]
Hello. Thanks for this excellent project!

When generating arrows, I find that one of the arrows go from the first instance of a View instead of the current one to the wrong wireframe. Is there a workaround for this?

For example:

```
@startuml
!include_once event-modeling-lib.iuml

$enableAutoAlias()
$enableAutoSpacing()

$configureWireframeLane(Manager)
$configureWireframeLane(Customer)
$configureEventLane(Booking, $context = Booking)

$wireframe(BookingDashboard, Manager)
$command(ConfirmReservation)
$event(ReservationConfirmed, Booking)
$view(Bookings)
$wireframe(BookingsIndex, Customer)

$command(CancelBooking)
$event(BookingCancelled, Booking)
$view(Bookings)
$wireframe(BookingsIndex, Customer)
$wireframe(BookingDashboard, Manager)
' Problematic arrow
$arrow(Bookings, BookingDashboard)

$renderEventModelingDiagram()
@enduml
```

Diagram:

![example](https://github.com/user-attachments/assets/1b34f645-ab1e-4dc7-85d4-67a17030295b)

**Comment by marriesvdh** [comment]
Hi Chris,

Thank you for your kind words!

I think the issue you are facing is that there are multiple elements with the same name. Because you are using the `$enableAutoAlias()` feature, subsequent elements with the same name have an alias appended with a number (see the documentation on this feature). The second `BookingDashboard` thus uses the alias `BookingDashboard1`, and similar for the `Bookings` view.

If you use `$arrow(Bookings1, BookingDashboard1)`, I expect your issue should be resolved.

**Comment by chriscz** [comment]
Hi Marries,

Ah, I see. It works, I glossed over the details and jumped straight into using the example :facepalm:

Thank you.
